- name: Enable RHEL repositories
  rhsm_repository:
    name: "{{ item }}"
    state: enabled
  loop: "{{ __ha_cluster_repos }}"
  when:
    - ansible_distribution == "RedHat"
    - ha_cluster_enable_repos
  # support systems which use custom repositories
  ignore_errors: yes

- name: Enable CentOS repositories
  command:
    cmd: "dnf config-manager --set-enabled {{ item | quote }}"
    # there doesn't seem to be a plugin for enabling already defined repos
    warn: no
  loop: "{{ __ha_cluster_repos }}"
  when:
    - ansible_distribution == "CentOS"
    - ha_cluster_enable_repos
  # support systems which use custom repositories
  ignore_errors: yes

- name: Install cluster packages
  package:
    name: "{{ \
      __ha_cluster_fullstack_node_packages \
      + \
      ha_cluster_fence_agent_packages \
    }}"
    state: present

# The user is created by installing pacemaker packages. We just need to set the
# password.
- name: Set hacluster password
  user:
    name: "hacluster"
    password: "{{ \
      ha_cluster_hacluster_password | \
      password_hash('sha512', ansible_hostname|replace('-','x')) \
    }}"
