# SPDX-License-Identifier: MIT
---
- name: Configure ticket constraint '{{
      constraint.id | default(constraint_index)
    }}'
  command:
    cmd: >
      pcs -f {{ __ha_cluster_tempfile_cib_xml.path | quote }}
      -- constraint ticket add
      {{ constraint.ticket | quote }}
      {{ constraint.resource.role | default() | quote }}
      {{ constraint.resource.id | quote }}
      {% if constraint.id | default() %}
        id={{ constraint.id | quote }}
      {% endif %}
      {% for option in constraint.options | default([]) %}
        {{ option.name | quote }}={{ option.value | quote }}
      {% endfor %}
  # We always need to create CIB to see whether it's the same as what is
  # already present in the cluster. However, we don't want to report it as a
  # change since the only thing which matters is pushing the resulting CIB to
  # the cluster.
  check_mode: no
  changed_when: not ansible_check_mode
